### ISSUE TITLE
Comparison between iz/chai/validator

### ISSUE THREAD

**Issue by foxx** [parris/iz#27]
I'm currently comparing some of the most popular validation libraries, specifically chai and validator, but also came across iz on [SO](http://stackoverflow.com/a/12658268/1267398). From what I can tell, chai/validator seems to cover all of the examples in the README, and a bunch of additional ones too. Could you explain what makes iz a better choice than these two libraries? Have I missed something? Thank you

**Comment by srph** [comment]
Unlike iz and validator, which are validation libraries, Chai is a test assertion library. It it used to test certain implementations in test suites. I've never tried Chai to play as the validator.

**Comment by parris** [comment]
Sorry for the delay response. Chai is for tests. Node validator at the time didn't cover the use cases I needed, and covered lots of other non-validation related things. Namely I didn't like santization and XSS all over my validation library.

Since then we've developed some worth while features no one else has like being able to validate entire objects, and being able to create JSON blob that has validation rules, which means you can do things like passing validation rules from the server side to the client side even in non-nodejs environments. We are more about validation for JS generically, and don't enforce a specific backend or frontend.

**Comment by foxx** [comment]
Beautiful, thank you for the in-depth response, this is clearer now.
