### ISSUE TITLE
iz.email(null) === true

### ISSUE THREAD

**Issue by gferrin** [parris/iz#29]
iz.email(null) === true

This caused a really weird error in my application. I don't think it's desired behavior.

**Comment by parris** [comment]
I saw this a few days ago. I looked for about 5 minutes and determined it
wasn't actually the validator rule. I bet its the 'required' vs 'not
required' nature of things in iz. As a work around if you use chaining and
add `.required()` I bet your bug will go away.

**Comment by parris** [comment]
Reviewing again.

`iz(null).email().required().valid` gives the correct response. 

2 possible tasks:
1. Updating the docs in order to make it more clear that the basic validators don't include `.required()`
2. Possibly make all basic validators respond as if they were `.required()`. This will break backwards compatibility for some applications. 

For now I may just add some documentation. If this comes up again I'll think about changing the API to accommodate.
